name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: cognityx/.github/.github/workflows/python-package-ci.yml@031a50e7c3a8addcd99c7326f45f17c3a1554bef
    with:
      python-version: "3.12"
      run-docs: true
      run-build: true
      run-release-verification: false
      install-all-extras: true
